let gameData = {
	"Siyer Genel Sorular": [
		{"values":{"cevap": " Peygamberimizin bir devlete ismini veren amcası", "soru": "Hz. Abbas"}},
		{"values":{"cevap": " Peygamberimizin babasının adı", "soru": "Abdullah"}},
		{"values":{"cevap": " Peygamberimizin ikinci doğan oğlu ", "soru": "Abdullah"}},
		{"values":{"cevap": " Peygamberimizin baba tarafından dedesi ", "soru": "Abdülmuttalip"}},
		{"values":{"cevap": " Peygamberimizin Saf suresinde geçen adı ", "soru": "Ahmed"}},
		{"values":{"cevap": " Peygamberimize ilk indirilen ayetlerin bulunduğu sure ", "soru": "Alak"}},
		{"values":{"cevap": " Peygamber isimlerinden sonra söylenir. Allah’ın selamı O’na olsun anlamındadır.", "soru": "Aleyhisselam"}},
		{"values":{"cevap": " Peygamberimizin amcası Ebu Talib’in oğlu. Efendimizin damadı ve İslam’ın 4. halifesi", "soru": "Hz. Ali"}},
		{"values":{"cevap": " Hicretten önce Medineli Müslümanlarla peygamberimiz arasında yapılan iki sözleşme.", "soru": "Akabe Biatları"}},
		{"values":{"cevap": " Salli ve Barik dualarında geçen peygamberimizin aile fertleri, eşleri, çocukları ve torunları.  ", "soru": "Âl-i Muhammed"}},
		{"values":{"cevap": " Peygamberimizin annesi ", "soru": "Amine "}},
		{"values":{"cevap": " Peygamberimizi hayatta görüp onun sohbetine katılan arkadaşları", "soru": "Ashab "}},
		{"values":{"cevap": " Hz Muhammed’in peygamberlik yaptığı ve varlığıyla şereflendirdiği devir", "soru": "Asrısaadet "}},
		{"values":{"cevap": " Kur’an-ı Kerim’de sureleri oluşturan Allah’ın sözleri.", "soru": "Âyet "}},
		{"values":{"cevap": " Peygamberimizin eşi. Hz. Ebu Bekir’in kızı.", "soru": "Hz. Ayşe "}},
		{"values":{"cevap": " Hicretin 2. yılında Müslümanlarla Mekkeli müşrikler arasında yapılan ilk büyük savaş.", "soru": "Bedir"}},
		{"values":{"cevap": " Peygamberimizin ilk müezzini.", "soru": "Bilal-i Habeşi "}},
		{"values":{"cevap": " Peygamberimizi Miraç Gecesi taşıyan binek.", "soru": "Burak "}},
		{"values":{"cevap": " Efendimizin peygamberliğinden önceki putlara tapılan dönem", "soru": "Cahiliye"}},
		{"values":{"cevap": " Peygamberimize Allah’tan vahiy getiren melek.", "soru": "Cebrail (as)"}},
		{"values":{"cevap": " Mekke döneminde Müslümanların toplandıkları Erkam isimli sahabenin evi.", "soru": "Darulerkam "}},
		{"values":{"cevap": " Müslümanlıktan önce Mekke’de kurulan siyasi, hukuki ve idari konuların konuşulduğu yer", "soru": "Darunnedve "}},
		{"values":{"cevap": " Allah’ın emriyle Kabe’yi yıkmak için yola çıkan Ebrehe komutasındaki orduya taşlarla yerle bir  eden kuşlar.", "soru": "Ebabil "}},
		{"values":{"cevap": " Peygamberimizin en yakın arkadaşı, İslam’ın ilk halifesi", "soru": "Hz. Ebu Bekir "}},
		{"values":{"cevap": " Peygamberimize karşı çıkan ve eziyet eden amcası ", "soru": "Ebu Leheb "}},
		{"values":{"cevap": " Peygamberimizi dedesinin vefatından sonra büyüten amcası", "soru": "Ebu Talip "}},
		{"values":{"cevap": " Peygamberimizin annesinin vefat ettiği köy", "soru": "Ebva "}},
		{"values":{"cevap": " Ev halkı anlamına gelen, peygamberimizin aile fertleri, eşleri, çocukları ve torunları.", "soru": "Ehlibeyt "}},
		{"values":{"cevap": " Kendilerine Tevrat, Zebur ve İncil gibi ilahi kitaplar verilen insanlar.", "soru": "Ehlikitap "}},
		{"values":{"cevap": " Peygamberimize güvenilirliğinden ötürü verilen unvan ", "soru": "Emin "}},
		{"values":{"cevap": " Mekke’den hicret edenleri karşılayıp evlerinde barındıran Medineli Müslümanlar", "soru": "Ensar "}},
		{"values":{"cevap": " Peygamberimiz Medine’ye geldiğinde kendisine bir ev yapılıncaya kadar evinde kaldığı sahabi ", "soru": "Ebu Eyyub El- Ensari "}},
		{"values":{"cevap": " Âlemin övüncü anlamına gelen peygamberimizin unvanı", "soru": "Fahrialem "}},
		{"values":{"cevap": " İncil’de Hz. İsa’nın kendisinden sonra geleceğini müjdelediği peygamber, Hz Muhammed ", "soru": "Faraklit "}},
		{"values":{"cevap": " Peygamberimizin Hz Ali ile evlendirdiği biricik kızı ", "soru": "Hz Fatıma "}},
		{"values":{"cevap": " Hz. Muhammed’in bizzat kendisinin katıldığı savaşlara verilen ad", "soru": "Gazve "}},
		{"values":{"cevap": " Müslümanların ilk hicret ettikleri yer  ", "soru": "Habeşistan "}},
		{"values":{"cevap": " Allah’ın sevgilisi anlamına gelen peygamberimizin unvanı", "soru": "Habibullah "}},
		{"values":{"cevap": " Peygamber Efendimize ait olan sözlere verilen ad ", "soru": "Hadis "}},
		{"values":{"cevap": " Peygamberimizin vefatından sonra yerine geçen devlet başkanı", "soru": "Halife "}},
		{"values":{"cevap": " Peygamberimizin sütannesi", "soru": "Halime "}},
		{"values":{"cevap": " Peygamberimizin Uhud Savaşı’nda şehit edilen amcası ", "soru": "Hz Hamza "}},
		{"values":{"cevap": " Hz Muhammed’in peygamberliğinden önce Mekke’de Allah’ın birliğine inanan kimseler", "soru": "Hanif "}},
		{"values":{"cevap": " Mekke ve Medine’nin ortak adları", "soru": "Haremeyn "}},
		{"values":{"cevap": " Peygamberimizin bir torunu. Soyundan gelenlere Şerif denir.  ", "soru": "Hz Hasan "}},
		{"values":{"cevap": " Peygamberimizin ilk eşi ", "soru": "Hz. Hatice "}},
		{"values":{"cevap": " Hz. Ali’nin kuşatılan kalenin kapısını kaldırıp kahraman olduğu savaş", "soru": "Hayber"}},
		{"values":{"cevap": " İnsanların en hayırlısı anlamında peygamberimizin unvanı", "soru": "Hayrulbeşer "}},
		{"values":{"cevap": " Saygı ifadesi olarak değerli kişilerin isminin önüne konan hitap kelimesi", "soru": "Hazreti "}},
		{"values":{"cevap": " Medine etrafına çukurlar kazılarak yapılan savunma savaşı", "soru": "Hendek"}},
		{"values":{"cevap": " Huneyn Savaşı’nın diğer adı ", "soru": "Hevazin"}},
		{"values":{"cevap": " 622 yılında peygamberimizin Mekke’den Medine’ye göçü ", "soru": "Hicret "}},
		{"values":{"cevap": " Peygamberimizin gençliğinde katıldığı Erdemliler Cemiyeti ", "soru": "Hilfulfudul "}},
		{"values":{"cevap": " Hz Muhammed’in bedensel ve ahlaki özelliklerini anlatan levha", "soru": "Hilye "}},
		{"values":{"cevap": " Peygamberimize ilk vahyin geldiği mağara ", "soru": "Hira "}},
		{"values":{"cevap": " Kutsal kitabı İncil, peygamberi Hz. İsa olan dine inanan kişi", "soru": "Hıristiyan "}},
		{"values":{"cevap": " 628 yılında Müslümanlarla Mekkeliler arasında yapılan anlaşma ", "soru": "Hudeybiye"}},
		{"values":{"cevap": " Mekke’nin fethinden sonra yapılan bir savaş", "soru": "Huneyn "}},
		{"values":{"cevap": " Peygamberimizin bir torunu. Soyundan gelenlere Seyyid denir.  ", "soru": "Hz Hüseyin "}},
		{"values":{"cevap": " Peygamberimizin amcası ve hanımını kaybettiği yıla verilen ad", "soru": "Hüzün"}},
		{"values":{"cevap": " Peygamberimizin Hz Mariye'den doğan oğlu ", "soru": "İbrahim "}},
		{"values":{"cevap": " Peygamberimizin soyundan geldiği büyük peygamber", "soru": "Hz İbrahim "}},
		{"values":{"cevap": " Peygamberimizin Miraç Gecesi Mekke’den Kudüs’e yaptığı yolculuk", "soru": "İsra "}},
		{"values":{"cevap": " Mekke’de bulunan Müslümanların kıblesi, beytullah", "soru": "Kâbe "}},
		{"values":{"cevap": " Kur’an’ın indirilmeye başlandığı gece", "soru": "Kadir "}},
		{"values":{"cevap": " Allah’ı inkar eden kişi ", "soru": "Kâfir "}},
		{"values":{"cevap": " Peygamberimizin ilk doğan oğlu ", "soru": "Kasım "}},
		{"values":{"cevap": " Lâ ilâhe illallah Muhammedun rasulullah cümlesi", "soru": "Kelime-i Tevhit "}},
		{"values":{"cevap": " Hz Muhammed’e cennette verilecek havuz", "soru": "Kevser "}},
		{"values":{"cevap": " Hicret sırasında Müslümanların yaptığı ilk mescid", "soru": "Kuba"}},
		{"values":{"cevap": " Peygamberimizin kabilesi ", "soru": "Kureyş "}},
		{"values":{"cevap": " Hz. Hatice’nin lakabı  ", "soru": "Kübra "}},
		{"values":{"cevap": " Peygamberimizin Kuran'da geçen bir adı ", "soru": "Mahmud "}},
		{"values":{"cevap": " Peygamberimizin çocuklarından İbrahim’in annesi olan hanımı", "soru": "Mariye "}},
		{"values":{"cevap": " Ateşe tapan kişi, ateşperest ", "soru": "Mecusi "}},
		{"values":{"cevap": " Peygamberimizin hicret ettiği ve kabrinin bulunduğu şehir", "soru": "Medine "}},
		{"values":{"cevap": " Hicretten sonra Müslümanlarla Medine’deki Yahudilerle yapılan anlaşma", "soru": "Medine Sözleşmesi "}},
		{"values":{"cevap": " Peygamberimizin savaşlarını inceleyen ilim dalı ", "soru": "Megazi "}},
		{"values":{"cevap": " Peygamberimizin doğum yeri  ", "soru": "Mekke "}},
		{"values":{"cevap": " Peygamberimizin kabrinin bulunduğu Medine’deki mescid", "soru": "Mescid-i Nebi "}},
		{"values":{"cevap": " Peygamberimizin doğduğu geceyi anmak için kutlanan kandil", "soru": "Mevlid "}},
		{"values":{"cevap": " Peygamberimizin Allah’ın huzuruna çıktığı gece", "soru": "Miraç "}},
		{"values":{"cevap": " Peygamberlerin Allah’ın izniyle gösterdikleri olağanüstü olaylar", "soru": "Mucize "}},
		{"values":{"cevap": " Mekke’nin Fethinden önce hicret edenlere verilen unvan ", "soru": "Muhacir "}},
		{"values":{"cevap": " Veysel Karani gibi peygamberimiz zamanında yaşayıp onu göremeyen Müslüman", "soru": "Muhadram "}},
		{"values":{"cevap": " Son peygambere olan biricik peygamberimizin adı", "soru": "Hz. Muhammed (sav)"}},
		{"values":{"cevap": " Hicretten önce Medine’ye giderek oradaki Müslümanlara İslam’ı öğreten genç sahabe", "soru": "Mus’ab b. Umeyr "}},
		{"values":{"cevap": " Peygamberimizin seçilmiş anlamında bir adı  ", "soru": "Mustafa "}},
		{"values":{"cevap": " Müslümanlarla Rumlar arasındaki ilk savaş", "soru": "Mute"}},
		{"values":{"cevap": " Allah’a ve ondan gelenlere tam inanmış kişi", "soru": "Mü'min "}},
		{"values":{"cevap": " Kalbiyle inanmadığı halde diliyle inandığını söyleyen ikiyüzlü fesat kimse", "soru": "Münafık "}},
		{"values":{"cevap": " Allah’a ortak koşan, putlara tap ", "soru": "Müşrik "}},
		{"values":{"cevap": " Peygamberimize yazılan övgü dolu şiir ", "soru": "Naat "}},
		{"values":{"cevap": " Kendisine ilahi kitap verilmeyen peygamber ", "soru": "Nebi "}},
		{"values":{"cevap": " Hira Mağarasının bulunduğu Mekke yakınlarındaki dağ", "soru": "Nur "}},
		{"values":{"cevap": " Peygamberlik kelimesinin eş anlamlısı", "soru": "Nübüvvet "}},
		{"values":{"cevap": " Kur’an’ın ilk emri ", "soru": "Oku "}},
		{"values":{"cevap": " İslam’ın ikinci halifesi ", "soru": "Hz  Ömer "}},
		{"values":{"cevap": " Allah’ın (cc) insanlara gönderdiği elçi,resul,nebi", "soru": "Peygamber "}},
		{"values":{"cevap": " 610 yılında Yüce Allah tarafından Hz Muhammed’e verilen görev ", "soru": "Peygamberlik "}},
		{"values":{"cevap": " İnsanların taştan tahtadan yaptıkları ve ibadet ettikleri heykeller ", "soru": "Put "}},
		{"values":{"cevap": " Taştan ve tahtadan yapılmış heykelleri ilah kabul edip onlara ibadet eden kişi ", "soru": "Putperest "}},
		{"values":{"cevap": " Kur’an’ın peygamberimize indirilmeye başlandığı ay", "soru": "Ramazan "}},
		{"values":{"cevap": " Hicret sırasında ilk cuma namazının kılındığı vadi ", "soru": "Ranuna "}},
		{"values":{"cevap": " Peygamberimizin hadislerini rivayet eden kişi ", "soru": "Ravi "}},
		{"values":{"cevap": " Peygamberimizin kabrinin adı ", "soru": "Ravza-i Mutahhara "}},
		{"values":{"cevap": " Peygamberimizin doğduğu hicri ay ", "soru": "Rebiyülevvel "}},
		{"values":{"cevap": " Hz Muhammed’in Miraç Gecesi bindiği binitlerden biri", "soru": "Refref "}},
		{"values":{"cevap": " Kendisine ilahi kitap verilen peygamber ", "soru": "Resul "}},
		{"values":{"cevap": " Hz Muhammed’in söz ve fiillerinin sözlü ve yazılı olarak sonraki nesillere aktarılması", "soru": "Rivayet "}},
		{"values":{"cevap": " Peygamberimizin Zeynep, Fatıma ve Ümmü Gülsüm'le berabar 4. kızı ", "soru": "Rukiye "}},
		{"values":{"cevap": " Peygamberimizi görüp sohbetine katılan Müslüman ", "soru": "Sahabe "}},
		{"values":{"cevap": " Peygamberimizin adı söylenince okunan dua ", "soru": "Salavat "}},
		{"values":{"cevap": " Peygamberimizin adı anıldığında salavat getirme ", "soru": "Salvele "}},
		{"values":{"cevap": " Peygamberimizin kendisinin katılmayıp sancağı bir arkadaşına verdiği küçük savaşlar", "soru": "Seriyye "}},
		{"values":{"cevap": " Hicret sırasında efendimizin Ebu Bekir’le birlikte saklandığı mağara ", "soru": "Sevr "}},
		{"values":{"cevap": " Hz Ebu Bekir’in efendimize sadakatinden dolayı aldığı isim ", "soru": "Sıddık "}},
		{"values":{"cevap": " Hz Muhammed’in hayatını araştıran ilim dalı", "soru": "Siyer "}},
		{"values":{"cevap": " Medine’deki mescidin etrafına yapılan eğitim amaçlı odalar ", "soru": "Suffa "}},
		{"values":{"cevap": " Hz Muhammed’in söz, fiil ve onaylarını içeren örnek davranışları, efendimizin yolu", "soru": "Sünnet "}},
		{"values":{"cevap": " Peygamber Efendimizin, 12 yaşında iken amcası Ebu Talip ile ticaret için gittiği şehir ", "soru": "Şam "}},
		{"values":{"cevap": " Ahirette peygamberimizin günahkârların affını Allah’tan istemesi ", "soru": "Şefaat "}},
		{"values":{"cevap": " Peygamberimizin ahlak ve alışkanlıklarını anlatan eserler ", "soru": "Şemail "}},
		{"values":{"cevap": " Peygamberimizin kız sütkardeşi  ", "soru": "Şeyma "}},
		{"values":{"cevap": " Allah’a eş ve ortak koşma, putlara tapma fiili ", "soru": "Şirk "}},
		{"values":{"cevap": " Peygamberimizin arkadaşları olan sahabeleri gören Müslüman ", "soru": "Tabiin "}},
		{"values":{"cevap": " Peygamberimizin davetini geri çeviren ve efendimize kötü davrananların Mekke yakınlarındaki köyü ", "soru": "Taif "}},
		{"values":{"cevap": " Peygamberimizin son savaşı ", "soru": "Tebük "}},
		{"values":{"cevap": " Peygamberimizin mübarek dişlerinin kırıldığı savaş ", "soru": "Uhud "}},
		{"values":{"cevap": " Peygamberimizin dadısı ", "soru": "Ümmü Eymen "}},
		{"values":{"cevap": " Peygamberimizin Zeynep, Fatıma ve Rukiye'yle berabar 4. kızı ", "soru": "Ümmü Gülsüm "}},
		{"values":{"cevap": " Peygamberimize Cebrail (as) aracılığıyla gelen Allah’ın mesajı.", "soru": "Vahiy "}},
		{"values":{"cevap": " Peygamberimize inen ayetleri yazan Müslümanlar ", "soru": "Vahiy Kâtibi "}},
		{"values":{"cevap": " Peygamberimizin vefat etmeden önce yüz binden fazla kişiye yaptığı konuşma", "soru": "Veda Hutbesi "}},
		{"values":{"cevap": " Peygamberimizin anne tarafından dedesi ", "soru": "Vehb "}},
		{"values":{"cevap": " Kutsal kitabı Tevrat olan dine inanan kişi ", "soru": "Yahudi "}},
		{"values":{"cevap": " Medine şehrinin hicretten önceki adı ", "soru": "Yesrib "}},
		{"values":{"cevap": " Mekke’de bulunan  mübarek su ", "soru": "Zemzem "}},
		{"values":{"cevap": " Peygamberimizin azadlı kölesi ve evlatlığı  olup ilk Müslümanlardandır.", "soru": "Hz Zeyd "}},
		{"values":{"cevap": " Peygamberimizin Rukiye, Fatıma ve Ümmü Gülsüm'le berabar 4. kızı ", "soru": "Zeyneb "}},
		{"values":{"cevap": " Hz Osman’a peygamberimizin iki kızıyla evlenmesinden dolayı verilen lakap", "soru": "Zinnureyn "}},
		{"values":{"cevap": " Peygamberimizin bir amcası ", "soru": "Zübeyr "}},
		{"values":{"cevap": " Hz Ali’nin kılıcının adı ", "soru": "Zülfikar "}}
	],
	"Peygamberimiz ve Sayılar": [
		{"values":{"cevap": " Annesi vefat ettiğinde peygamberimizin yaşı ", "soru": "6"}},
		{"values":{"cevap": " Dedesi Abdulmuttalip öldüğünde peygamberimizin yaşı ", "soru": "8"}},
		{"values":{"cevap": " İslam’a davetin gizli yapıldığı yıl sayısı ", "soru": "3"}},
		{"values":{"cevap": " Peygamberimizin ilk evliliğini yaptığı yaşı ", "soru": "25"}},
		{"values":{"cevap": " Peygamberimizin çocuklarının sayısı ", "soru": "7"}},
		{"values":{"cevap": " Efendimiz peygamber olduğundaki yaşı ", "soru": "40"}},
		{"values":{"cevap": " Efendimizin yaklaşık olarak peygamberlik süresi ", "soru": "23"}},
		{"values":{"cevap": " Peygamber Efendimizin vefat yaşı ", "soru": "63"}},
		{"values":{"cevap": " Peygamberimizin miladi doğum yılı ", "soru": "571"}},
		{"values":{"cevap": " Kur’an’ın indirilmeye başlandığı yıl ", "soru": "610"}},
		{"values":{"cevap": " Peygamberimizin Mekke’den Medine’ye hicret yılı ", "soru": "622"}},
		{"values":{"cevap": " Bedir Savaşının yapıldığı sene ", "soru": "624"}},
		{"values":{"cevap": " Uhud Savaşının yapıldığı sene ", "soru": "625"}},
		{"values":{"cevap": " Hendek Savaşının yapıldığı sene ", "soru": "627"}},
		{"values":{"cevap": " Hudeybiye Anlaşmasının yapıldığı yıl ", "soru": "628"}},
		{"values":{"cevap": " Mekke’nin fethedildiği yıl ", "soru": "630"}},
		{"values":{"cevap": " Peygamberimizin vefat yılı ", "soru": "632"}}
	],
	"Peygamberimiz ve Yerler": [
		{"values":{"cevap": " Hicretten önce Medineli Müslümanlarla peygamberimiz arasında iki sözleşme yapılan yer.", "soru": "Akabe"}},
		{"values":{"cevap": " Hicretin 2. yılında Müslümanlarla Mekkeli müşrikler arasında yapılan ilk büyük savaşın yapıldığı yer.", "soru": "Bedir"}},
		{"values":{"cevap": " Mekke döneminde Müslümanların toplandıkları Erkam isimli sahabenin evi.", "soru": "Darulerkam "}},
		{"values":{"cevap": " Müslümanlıktan önce Mekke’de kurulan siyasi, hukuki ve idari konuların konuşulduğu yer", "soru": "Darunnedve "}},
		{"values":{"cevap": " Peygamberimizin annesinin vefat ettiği köy", "soru": "Ebva "}},
		{"values":{"cevap": " Müslümanların ilk hicret ettikleri yer  ", "soru": "Habeşistan "}},
		{"values":{"cevap": " Hz. Ali’nin kuşatılan kalenin kapısını kaldırıp kahraman olduğu savaşın yapıldığı yer", "soru": "Hayber"}},
		{"values":{"cevap": " Peygamberimize ilk vahyin geldiği mağara ", "soru": "Hira "}},
		{"values":{"cevap": " 628 yılında Müslümanlarla Mekkeliler arasında anlaşma yapılan yer", "soru": "Hudeybiye"}},
		{"values":{"cevap": " Mekke’nin fethinden sonra yapılan Hevazin savaşının yeri", "soru": "Huneyn "}},
		{"values":{"cevap": " Peygamberimizin Miraç Gecesi Mekke’den çıkıp gittiği şehir", "soru": "Kudüs"}},
		{"values":{"cevap": " Mekke’de bulunan Müslümanların kıblesi, beytullah", "soru": "Kâbe "}},
		{"values":{"cevap": " Mekke’de içinde Kâbe'nin bulunduğu mescit", "soru": "Mescid-i Haram "}},
		{"values":{"cevap": " Kudüs’te bulunan kutsal mescit", "soru": "Mescid-i Aksa "}},
		{"values":{"cevap": " Medine’de içinde peygamberimizin kabrinin bulunduğu mescit", "soru": "Mescid-i Nebi "}},
		{"values":{"cevap": " Hz Muhammed’e cennette verilecek havuz", "soru": "Kevser "}},
		{"values":{"cevap": " Hicret sırasında Müslümanların yaptığı ilk mescid", "soru": "Kuba"}},
		{"values":{"cevap": " Peygamberimizin hicret ettiği ve kabrinin bulunduğu şehir", "soru": "Medine "}},
		{"values":{"cevap": " Peygamberimizin doğduğu şehir ", "soru": "Mekke "}},
		{"values":{"cevap": " Müslümanlarla Rumlar arasındaki ilk savaşın yapıldığı yer", "soru": "Mute"}},
		{"values":{"cevap": " Hira Mağarasının bulunduğu Mekke yakınlarındaki dağ", "soru": "Nur "}},
		{"values":{"cevap": " Kur’an’ın peygamberimize indirilmeye başlandığı ay", "soru": "Ramazan "}},
		{"values":{"cevap": " Hicret sırasında ilk cuma namazının kılındığı vadi ", "soru": "Ranuna "}},
		{"values":{"cevap": " Peygamberimizin kabrinin adı ", "soru": "Ravza-i Mutahhara "}},
		{"values":{"cevap": " Hicret sırasında efendimizin Ebu Bekir’le birlikte saklandığı mağara ", "soru": "Sevr "}},
		{"values":{"cevap": " Medine’deki mescidin etrafına yapılan eğitim amaçlı odalara verilen isim ", "soru": "Suffa "}},
		{"values":{"cevap": " Peygamber Efendimizin, 12 yaşında iken amcası Ebu Talip ile ticaret için gittiği şehir ", "soru": "Şam "}},
		{"values":{"cevap": " Peygamberimizin davetini geri çeviren ve efendimize kötü davrananların Mekke yakınlarındaki köyü ", "soru": "Taif "}},
		{"values":{"cevap": " Peygamberimizin katıldığı son savaşın yapıldığı yer ", "soru": "Tebük "}},
		{"values":{"cevap": " Peygamberimizin amcası Hz Hamza'nın şehit olduğu savaşın yapıldığı yer ", "soru": "Uhud "}},
		{"values":{"cevap": " Medine şehrinin hicretten önceki adı ", "soru": "Yesrib "}}
	],
	"Peygamberimizin Akrabaları ve Arkadaşları": [
		{"values":{"cevap": "Peygamberimizin bir devlete ismini veren amcası", "soru": "Hz. Abbas"}},
		{"values":{"cevap": "Peygamberimizin babasının adı", "soru": "Abdullah"}},
		{"values":{"cevap": " Peygamberimizin ikinci doğan oğlu ", "soru": "Abdullah"}},
		{"values":{"cevap": " Peygamberimizin baba tarafından dedesi ", "soru": "Abdülmuttalip"}},
		{"values":{"cevap": " Peygamberimizin amcası Ebu Talib’in oğlu. Efendimizin damadı ve İslam’ın 4. halifesi", "soru": "Hz. Ali"}},
		{"values":{"cevap": " Salli ve Barik dualarında geçen peygamberimizin aile fertleri, eşleri, çocukları ve torunları. ", "soru": "Âl-i Muhammed"}},
		{"values":{"cevap": " Peygamberimizin annesi ", "soru": "Amine "}},
		{"values":{"cevap": " Peygamberimizi hayatta görüp onun sohbetine katılan arkadaşları", "soru": "Ashab "}},
		{"values":{"cevap": " Peygamberimizin eşi. Hz. Ebu Bekir’in kızı.", "soru": "Hz. Ayşe "}},
		{"values":{"cevap": " Peygamberimizin ilk müezzini.", "soru": "Bilal-i Habeşi "}},
		{"values":{"cevap": " Peygamberimizin en yakın arkadaşı, İslam’ın ilk halifesi", "soru": "Hz. Ebu Bekir "}},
		{"values":{"cevap": " Peygamberimize karşı çıkan ve eziyet eden amcası ", "soru": "Ebu Leheb "}},
		{"values":{"cevap": " Peygamberimizi dedesinin vefatından sonra büyüten amcası", "soru": "Ebu Talip "}},
		{"values":{"cevap": " Ev halkı anlamına gelen, peygamberimizin aile fertleri, eşleri, çocukları ve torunları.", "soru": "Ehlibeyt "}},
		{"values":{"cevap": " Peygamberimiz Medine’ye geldiğinde kendisine bir ev yapılıncaya kadar evinde kaldığı sahabi ", "soru": "Hz Eyyub El- Ensari "}},
		{"values":{"cevap": " Peygamberimizin Hz Ali ile evlendirdiği kızı ", "soru": "Hz Fatıma "}},
		{"values":{"cevap": " Peygamberimizin sütannesi", "soru": "Halime "}},
		{"values":{"cevap": " Peygamberimizin Uhud Savaşı’nda şehit edilen amcası ", "soru": "Hz Hamza "}},
		{"values":{"cevap": " Peygamberimizin bir torunu. Soyundan gelenlere Şerif denir.  ", "soru": "Hz Hasan "}},
		{"values":{"cevap": " Peygamberimizin ilk eşi ", "soru": "Hz. Hatice "}},
		{"values":{"cevap": " Peygamberimizin bir torunu. Soyundan gelenlere Seyyid denir.  ", "soru": "Hz Hüseyin "}},
		{"values":{"cevap": "Peygamberimizin Hz Mariye'den doğan oğlu ", "soru": "İbrahim "}},
		{"values":{"cevap": " Peygamberimizin soyundan geldiği Halilullah lakaplı büyük peygamber", "soru": "Hz İbrahim "}},
		{"values":{"cevap": " Peygamberimizin soyundan geldiği Hz İbrahim'in oğlu olan peygamber", "soru": "Hz İsmail "}},
		{"values":{"cevap": " Peygamberimizin ilk doğan oğlu ", "soru": "Kasım "}},
		{"values":{"cevap": " Hz. Hatice’nin lakabı  ", "soru": "Kübra "}},
		{"values":{"cevap": " Peygamberimizin çocuklarından İbrahim’in annesi olan hanımı", "soru": "Mariye "}},
		{"values":{"cevap": " Hicretten önce Medine’ye giderek oradaki Müslümanlara İslam’ı öğreten genç sahabe", "soru": "Mus’ab b. Umeyr "}},
		{"values":{"cevap": " İslam’ın ikinci halifesi ", "soru": "Hz  Ömer "}},
		{"values":{"cevap": " Peygamberimizin Zeynep, Fatıma ve Ümmü Gülsüm'le berabar 4. kızı  ", "soru": "Rukiye "}},
		{"values":{"cevap": " Peygamberimizin kız sütkardeşi  ", "soru": "Şeyma "}},
		{"values":{"cevap": " Peygamberimizin dadısı ", "soru": "Ümmü Eymen "}},
		{"values":{"cevap": " Peygamberimizin Zeynep, Fatıma ve Rukiye'yle berabar 4. kızı ", "soru": "Ümmü Gülsüm "}},
		{"values":{"cevap": " Peygamberimizin anne tarafından dedesi ", "soru": "Vehb "}},
		{"values":{"cevap": " Peygamberimizin azadlı kölesi ve evlatlığı  olup ilk Müslümanlardandır.", "soru": "Hz Zeyd "}},
		{"values":{"cevap": " Peygamberimizin Rukiye, Fatıma ve Ümmü Gülsüm'le berabar 4. kızı ", "soru": "Zeyneb "}},
		{"values":{"cevap": " Hz Osman’a peygamberimizin iki kızıyla evlenmesinden dolayı verilen lakap", "soru": "Zinnureyn "}},
		{"values":{"cevap": " Peygamberimizin ismi alfabemizin son harfiyle başlayan amcası ", "soru": "Zübeyr "}},
		{"values":{"cevap": " Peygamberimizin ismi alfabemizin 10. harfiyle başlayan amcası ", "soru": "Haris "}},
		{"values":{"cevap": " Hz Ebu Bekir’in efendimize sadakatinden dolayı aldığı isim ", "soru": "Sıddık "}}
	],
};